#version: '3.0'
#services:
#  company_manager_db:
#    container_name: pg_container
#    image: postgres
#    restart: always
#    env_file:
#      - database.env
#    ports:
#      - "5432:5432"
#    volumes:
#        - $HOME/Programy/docker/PostgreSql-Snippets/infile:/infile
#        - pg_data:/var/lib/docker/volumes/pgdate/_data
#  pgadmin:
#    container_name: pgadmin4_container
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5050:80"
#
#volumes:
#  pg_data: